version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: sales
        description: Sales Table
        identifier: gz_raw_sals
      - name: product
        description: Product Table
        identifier: raw_gz_product

      - name: ship
        description: Ship Table
        identifier: raw_gz_ship

